-- Rinova BD user-supplied catalogue expansion
-- Uses columns verified in the live D1 products table.

UPDATE products SET category_id = 1, updated_at = CURRENT_TIMESTAMP WHERE id = 1 AND category_id IS NULL;
UPDATE products SET category_id = 2, updated_at = CURRENT_TIMESTAMP WHERE id = 2 AND category_id IS NULL;
UPDATE products SET category_id = 1, updated_at = CURRENT_TIMESTAMP WHERE id = 3 AND category_id IS NULL;
UPDATE products SET category_id = 5, updated_at = CURRENT_TIMESTAMP WHERE id = 4 AND category_id IS NULL;

INSERT OR IGNORE INTO products(category_id, name, slug, sku, description, short_description, price, compare_at_price, cost_price, image_url, barcode, weight_grams, stock, low_stock_threshold, min_order_qty, status, tags_json, specs_json, volume_tiers_json, featured, active, updated_at) VALUES
(3, 'Coral Glow Makeup Edit', 'coral-glow-makeup-edit', 'RNV-FM-001', 'A warm coral makeup edit featuring blush and lip colour for an easy, sunlit look.', 'Warm coral shades for cheeks and lips.', 1290, 1490, 780, '/assets/coral-glow-makeup-edit.png', 'RNV-FM-001', 180, 20, 5, 1, 'active', '["blush","coral","face makeup"]', '[]', '[]', 1, 1, CURRENT_TIMESTAMP),
(3, 'Coral Crush Blush Duo', 'coral-crush-blush-duo', 'RNV-FM-002', 'A vibrant coral blush duo in sleek compact packaging for buildable everyday colour.', 'Buildable coral blush duo.', 750, 890, 420, '/assets/coral-crush-blush-duo.png', 'RNV-FM-002', 45, 24, 5, 1, 'active', '["blush","coral","face makeup"]', '[]', '[]', 1, 1, CURRENT_TIMESTAMP),
(3, 'Rose Gold Baked Blush Compact', 'rose-gold-baked-blush-compact', 'RNV-FM-003', 'A soft rose baked blush in a gold compact for a polished, luminous finish.', 'Soft rose baked blush compact.', 650, 790, 360, '/assets/rose-gold-baked-blush.png', 'RNV-FM-003', 42, 22, 5, 1, 'active', '["blush","rose","face makeup"]', '[]', '[]', 0, 1, CURRENT_TIMESTAMP),
(2, 'Himalaya Face Wash Collection', 'himalaya-face-wash-collection', 'RNV-FC-001', 'A six-piece Himalaya face-wash collection for shoppers comparing gentle daily cleansing options.', 'Six face-wash options in one collection.', 1090, 1290, 720, '/assets/himalaya-face-wash-collection.png', 'RNV-FC-001', 900, 10, 3, 1, 'active', '["face wash","himalaya","skin care"]', '[]', '[]', 1, 1, CURRENT_TIMESTAMP),
(2, 'Himalaya Purifying Neem Face Wash 150ml White', 'himalaya-purifying-neem-face-wash-150ml-white', 'RNV-FC-002', 'Himalaya Purifying Neem Face Wash in a 150ml tube with neem and turmeric cleansing care.', 'Neem and turmeric face wash, 150ml.', 350, 420, 220, '/assets/himalaya-neem-face-wash-white.png', 'RNV-FC-002', 170, 28, 5, 1, 'active', '["face wash","neem","himalaya"]', '[]', '[]', 1, 1, CURRENT_TIMESTAMP),
(2, 'Himalaya Purifying Neem Face Wash 50ml', 'himalaya-purifying-neem-face-wash-50ml', 'RNV-FC-003', 'A compact 50ml Himalaya Purifying Neem Face Wash for a simple everyday cleansing routine.', 'Compact neem face wash, 50ml.', 220, 280, 135, '/assets/himalaya-neem-face-wash-50ml.png', 'RNV-FC-003', 65, 30, 5, 1, 'active', '["face wash","neem","travel size"]', '[]', '[]', 0, 1, CURRENT_TIMESTAMP),
(2, 'Himalaya Purifying Neem Face Wash 150ml Green', 'himalaya-purifying-neem-face-wash-150ml-green', 'RNV-FC-004', 'Himalaya Purifying Neem Face Wash in a 150ml green tube for a refreshing daily cleanse.', 'Refreshing neem face wash, 150ml.', 390, 450, 250, '/assets/himalaya-neem-face-wash-150ml.png', 'RNV-FC-004', 170, 26, 5, 1, 'active', '["face wash","neem","himalaya"]', '[]', '[]', 1, 1, CURRENT_TIMESTAMP);
