const API_BASE = window.RINOVA_API_BASE || (window.location.hostname.includes('localhost') ? 'http://localhost:8787/api' : '/api');
const createVisitorKey = () => typeof crypto.randomUUID === 'function' ? crypto.randomUUID() : `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const state = { products: [], bag: JSON.parse(localStorage.getItem('rinova-bag') || '[]'), filter: 'all', search: '', chatMessages: [], marketingBanners: [], visitorKey: localStorage.getItem('rinova-chat-visitor') || `visitor-${createVisitorKey()}`, adminPreview: new URLSearchParams(window.location.search).get('admin_preview') === '1' && Boolean(sessionStorage.getItem('rinova-admin-token')), adminPreviewMode: sessionStorage.getItem('rinova-admin-mode') === 'edit' ? 'edit' : 'view' };
const money = (value) => `৳${Number(value || 0).toLocaleString('en-BD')}`;
const $ = (selector) => document.querySelector(selector);
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
const icon = (name, className = '') => window.RinovaIcons?.svg(name, className) || '';
localStorage.setItem('rinova-chat-visitor', state.visitorKey);
function track(name, params = {}) { return window.rinovaAnalytics?.track ? window.rinovaAnalytics.track(name, params) : (window.dataLayer = window.dataLayer || [], window.dataLayer.push({ event: name, ...params })); }
function toast(message) { const node = $('#toast'); node.textContent = message; node.classList.add('show'); setTimeout(() => node.classList.remove('show'), 2600); }
function saveBag() { localStorage.setItem('rinova-bag', JSON.stringify(state.bag)); renderBag(); }
async function api(path, options = {}) { const response = await fetch(`${API_BASE}${path}`, { ...options, headers: { 'Content-Type': 'application/json', ...(options.headers || {}) } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Could not load shop data'); return data; }
function renderCategories(categories) { $('#category-grid').innerHTML = categories.map((category) => `<a class="category-card" href="#shop" data-category="${escapeHtml(category.slug)}"><img src="${escapeHtml(category.imageUrl || '/assets/beauty-flatlay.jpg')}" alt="${escapeHtml(category.name)}" loading="lazy" /><span>${escapeHtml(category.name)} <b>${icon('arrowUpRight')}</b></span></a>`).join(''); document.querySelectorAll('.category-card').forEach((card) => card.addEventListener('click', () => { state.filter = card.dataset.category; document.querySelectorAll('.filter').forEach((filter) => filter.classList.toggle('active', filter.dataset.filter === state.filter)); renderProducts(); renderMarketingBanners(state.marketingBanners); track('category_select', { category: state.filter }); })); }
function searchText(product) { return [product.name, product.description, product.shortDescription, product.categoryName, product.categorySlug, product.sku, product.barcode, product.tagsJson].map((value) => String(value || '').normalize('NFKC').toLocaleLowerCase()).join(' '); }
function visibleProducts() { let products = state.filter === 'featured' ? state.products.filter((product) => product.featured || (Number(product.reviewCount || 0) > 0 && Number(product.rating || 0) >= 4.5)) : state.filter === 'all' ? state.products : state.products.filter((product) => product.categorySlug === state.filter); const terms = state.search.trim().normalize('NFKC').toLocaleLowerCase().split(/\s+/).filter(Boolean); if (terms.length) products = products.filter((product) => { const haystack = searchText(product); return terms.every((term) => haystack.includes(term)); }); const unique = new Map(); products.forEach((product) => { const key = String(product.id ?? product.slug ?? product.name).toLowerCase(); if (!unique.has(key)) unique.set(key, product); }); return Array.from(unique.values()); }
function parseProductBadges(value) { let parsed = []; try { parsed = Array.isArray(value) ? value : JSON.parse(value || '[]'); } catch {} return Array.isArray(parsed) ? parsed.map((item) => String(item).toLowerCase()).filter((item) => ['hot', 'new', 'stockout', 'out', 'instock'].includes(item)) : []; }
function productBadges(product) { const labels = { hot: 'Hot', new: 'New', out: 'Stock Out' }; const selected = parseProductBadges(product.badgesJson || product.badges).map((badge) => badge === 'stockout' ? 'out' : badge).filter((badge) => badge !== 'instock' && labels[badge]); return Array.from(new Set(selected)).map((badge) => `<span class="product-badge badge-${badge}">${labels[badge]}</span>`).join(''); }
function parseProductMedia(product) { let parsed = []; try { parsed = JSON.parse(product.mediaJson || '[]'); } catch {} const media = (Array.isArray(parsed) ? parsed : []).map((item) => ({ type: item?.type === 'video' ? 'video' : 'image', url: typeof item === 'string' ? item : item?.url, alt: item?.alt || product.name })).filter((item) => /^(https:\/\/|\/assets\/|\/media\/)/i.test(String(item.url || ''))); const primary = String(product.imageUrl || '').trim(); if (primary && !media.some((item) => item.url === primary)) media.unshift({ type: 'image', url: primary, alt: product.name }); return media.length ? media : [{ type: 'image', url: '/assets/beauty-flatlay.jpg', alt: product.name }]; }
function productCardImage(product) { return parseProductMedia(product).find((item) => item.type === 'image')?.url || '/assets/beauty-flatlay.jpg'; }
function renderProducts() { const products = visibleProducts(); $('#product-grid').innerHTML = products.length ? products.map((product) => { const detailHref = `/products/${encodeURIComponent(product.slug || product.id)}${state.adminPreview ? '?admin_preview=1' : ''}`; const rating = Number(product.rating || 0); const adminEditLink = state.adminPreview && state.adminPreviewMode === 'edit' ? `<a class="admin-preview-edit" target="_parent" href="/admin/?view=products&edit=${encodeURIComponent(product.id)}">Edit product ${icon('arrowUpRight')}</a>` : ''; return `<article class="product-card" role="link" tabindex="0" data-product-detail="${escapeHtml(detailHref)}"><a class="product-image-wrap product-detail-link" href="${detailHref}"><img class="product-image" src="${escapeHtml(productCardImage(product))}" alt="${escapeHtml(product.name)}" loading="lazy" /><div class="product-badges">${productBadges(product)}</div></a><div class="product-info"><h3 class="product-name"><a class="product-detail-link" href="${detailHref}">${escapeHtml(product.name)}</a></h3><div class="product-rating" aria-label="${rating ? `Rated ${rating.toFixed(1)} out of 5` : 'Not yet rated'}">${rating ? `${icon('star', 'product-rating-icon')} <span>${rating.toFixed(1)}</span>` : '<span>New</span>'}</div><div class="product-price"><strong>${money(product.price)}</strong>${product.compareAtPrice ? `<del>${money(product.compareAtPrice)}</del>` : ''}</div><div class="product-actions"><button class="product-quick product-add" data-add="${product.id}" ${product.stock < 1 ? 'disabled' : ''}>Add to Cart ${icon('plus')}</button><button class="product-shop-now" data-add="${product.id}" ${product.stock < 1 ? 'disabled' : ''}>Shop Now ${icon('arrowRight')}</button></div>${adminEditLink}</div></article>`; }).join('') : '<div class="loading">No products in this edit yet.</div>'; document.querySelectorAll('[data-add]').forEach((button) => button.addEventListener('click', (event) => { event.preventDefault(); event.stopPropagation(); addToBag(Number(button.dataset.add)); if (button.classList.contains('product-shop-now')) toggleDrawer(true); })); document.querySelectorAll('.product-card[data-product-detail]').forEach((card) => { const goToDetails = () => { window.location.href = card.dataset.productDetail; }; card.addEventListener('click', (event) => { if (event.target.closest('a,button')) return; goToDetails(); }); card.addEventListener('keydown', (event) => { if ((event.key === 'Enter' || event.key === ' ') && !event.target.closest('a,button')) { event.preventDefault(); goToDetails(); } }); }); }
window.addEventListener('message', (event) => { if (event.origin !== window.location.origin || event.data?.type !== 'rinova-admin-preview-mode' || !state.adminPreview) return; const nextMode = event.data.mode === 'edit' ? 'edit' : 'view'; if (state.adminPreviewMode !== nextMode) { state.adminPreviewMode = nextMode; renderProducts(); } });
function addToBag(productId) { const product = state.products.find((item) => item.id === productId); if (!product) return; const existing = state.bag.find((item) => item.id === productId); const minimum = Math.max(1, Number(product.minOrderQty || 1)); const maximum = Number(product.stock || 0); if (existing) existing.quantity = Math.min(maximum || existing.quantity + 1, existing.quantity + 1); else state.bag.push({ id: product.id, name: product.name, price: product.price, imageUrl: productCardImage(product), quantity: minimum, stock: maximum, minOrderQty: minimum, categoryName: product.categoryName, categorySlug: product.categorySlug }); saveBag(); toast(`${product.name} added to your bag`); track('add_to_cart', { currency: 'BDT', value: Number(product.price || 0) * minimum, items: [window.rinovaAnalytics?.item(product, minimum) || { item_id: product.slug, item_name: product.name, price: Number(product.price || 0), quantity: minimum, item_category: product.categoryName || product.categorySlug }] }); }
function removeFromBag(productId) { const item = state.bag.find((entry) => entry.id === productId); state.bag = state.bag.filter((entry) => entry.id !== productId); saveBag(); if (item) track('remove_from_cart', { currency: 'BDT', value: Number(item.price || 0) * Number(item.quantity || 1), items: [window.rinovaAnalytics?.item(item, item.quantity) || { item_id: item.id, item_name: item.name, price: Number(item.price || 0), quantity: Number(item.quantity || 1) }] }); }
function changeBagQuantity(productId, direction) { const item = state.bag.find((entry) => Number(entry.id) === Number(productId)); if (!item) return; const minimum = Math.max(1, Number(item.minOrderQty || 1)); const maximum = Number(item.stock || 0); const next = Number(item.quantity || minimum) + direction; if (next < minimum) return removeFromBag(productId); item.quantity = maximum ? Math.min(maximum, next) : next; saveBag(); }
function renderBag() { const totalItems = state.bag.reduce((sum, item) => sum + Number(item.quantity || 0), 0); $('#bag-count').textContent = totalItems; const total = state.bag.reduce((sum, item) => sum + Number(item.price || 0) * Number(item.quantity || 0), 0); $('#bag-total').textContent = money(total); $('#bag-items').innerHTML = state.bag.length ? state.bag.map((item) => `<div class="bag-item"><img src="${escapeHtml(item.imageUrl)}" alt="${escapeHtml(item.name)}" /><div><strong>${escapeHtml(item.name)}</strong><div class="quantity-stepper bag-stepper"><button data-bag-qty="${item.id}" data-direction="-1" aria-label="Decrease ${escapeHtml(item.name)}">${icon('minus')}</button><span>${Number(item.quantity || 0)}</span><button data-bag-qty="${item.id}" data-direction="1" aria-label="Increase ${escapeHtml(item.name)}">${icon('plus')}</button></div><small>${money(item.price)} each</small></div><button data-remove="${item.id}" aria-label="Remove ${escapeHtml(item.name)}">${icon('close')}</button></div>`).join('') : '<div class="bag-empty">Your bag is waiting for a little ritual.</div>'; document.querySelectorAll('[data-remove]').forEach((button) => button.addEventListener('click', () => removeFromBag(Number(button.dataset.remove)))); document.querySelectorAll('[data-bag-qty]').forEach((button) => button.addEventListener('click', () => changeBagQuantity(Number(button.dataset.bagQty), Number(button.dataset.direction)))); }
function toggleDrawer(open) {
  $('#bag-drawer').classList.toggle('open', open);
  $('#bag-drawer').setAttribute('aria-hidden', String(!open));
  // The bottom tab bar sits above the drawer, and on a phone it covered the delivery note
  // and clipped the checkout button. The bag owns the screen while it is open.
  document.body.classList.toggle('bag-open', open);
  if (open) renderBagDeliveryNote();
}

/**
 * The bag quoted "৳90 inside Dhaka, ৳150 outside Dhaka" as fixed text, so it kept showing the
 * old charges after the owner changed them in Settings — the same fault as the checkout note.
 */
let bagDeliveryPromise = null;
function renderBagDeliveryNote() {
  const node = document.getElementById('bag-delivery-note');
  if (!node) return;
  bagDeliveryPromise = bagDeliveryPromise || fetch(`${API_BASE}/config`).then((response) => (response.ok ? response.json() : null)).catch(() => null);
  bagDeliveryPromise.then((payload) => {
    const target = document.getElementById('bag-delivery-note');
    if (!target || !payload) return;
    const inside = Number(payload.delivery?.dhaka || 0);
    const outside = Number(payload.delivery?.outsideDhaka || 0);
    if (inside || outside) target.textContent = `Delivery is calculated automatically at checkout: ${money(inside)} inside Dhaka, ${money(outside)} outside Dhaka.`;
  });
}
function toggleMobileNav(open) { const nav = $('#mobile-nav'); const backdrop = $('#mobile-nav-backdrop'); nav?.classList.toggle('open', open); backdrop?.classList.toggle('open', open); nav?.setAttribute('aria-hidden', String(!open)); backdrop?.setAttribute('aria-hidden', String(!open)); document.body.classList.toggle('menu-open', open); }
function openSearch() { const overlay = $('#search-overlay'); overlay?.classList.add('open'); overlay?.setAttribute('aria-hidden', 'false'); document.body.classList.add('search-open'); window.setTimeout(() => $('#site-search')?.focus(), 60); }
function closeSearch() { const overlay = $('#search-overlay'); overlay?.classList.remove('open'); overlay?.setAttribute('aria-hidden', 'true'); document.body.classList.remove('search-open'); }
function submitSearch(event) { event.preventDefault(); const input = $('#site-search'); const query = input.value.trim(); if (!query) return input.focus(); state.search = query; state.filter = 'all'; document.querySelectorAll('.filter').forEach((filter) => filter.classList.toggle('active', filter.dataset.filter === 'all')); renderProducts(); closeSearch(); $('#shop')?.scrollIntoView({ behavior: 'smooth', block: 'start' }); toast(`Showing results for “${query}”`); track('search', { search_term: query.slice(0, 80) }); }
function checkout() { if (!state.bag.length) return toast('Add a product before checkout'); const items = state.bag.map((item) => window.rinovaAnalytics?.item(item, item.quantity) || { item_id: item.id, item_name: item.name, price: Number(item.price || 0), quantity: Number(item.quantity || 1) }); const value = items.reduce((sum, item) => sum + Number(item.price || 0) * Number(item.quantity || 0), 0); track('begin_checkout', { currency: 'BDT', value, items }); window.location.href = '/checkout.html'; }
function bannerMatchesFilter(banner) { return !banner.categorySlug || state.filter === 'all' || state.filter === 'featured' || banner.categorySlug === state.filter; }
function bannerVisual(banner) { const image = String(banner.imageUrl || '').trim(); return /^(https:\/\/|\/assets\/|\/media\/)/i.test(image) ? `<img src="${escapeHtml(image)}" alt="" loading="lazy" />` : `<span class="marketing-banner-mark" aria-hidden="true">${icon('sparkle')}</span>`; }
function bannerContent(banner) { return `<span class="marketing-banner-copy"><small>${escapeHtml(banner.eyebrow || 'RINOVA EDIT')}</small><strong>${escapeHtml(banner.title || banner.body || 'A softer edit awaits')}</strong>${banner.body ? `<span>${escapeHtml(banner.body)}</span>` : ''}</span>`; }
function bannerCard(banner, extraClass = '') { const href = String(banner.linkUrl || '').trim(); const promotionAttrs = `data-promotion-id="${escapeHtml(String(banner.id || banner.title || 'rinova-promotion'))}" data-promotion-name="${escapeHtml(banner.title || 'Rinova promotion')}"`; const content = `${bannerVisual(banner)}${bannerContent(banner)}<span class="marketing-banner-arrow" aria-hidden="true">${icon('arrowUpRight')}</span>`; return href ? `<a class="marketing-banner-card ${extraClass}" ${promotionAttrs} href="${escapeHtml(href)}">${content}</a>` : `<div class="marketing-banner-card ${extraClass}" ${promotionAttrs}>${content}</div>`; }
function renderMarketingBanners(banners) { const root = $('#marketing-marquee-root'); if (!root) return; const marquee = (banners || []).filter((banner) => banner.placement === 'marquee' && bannerMatchesFilter(banner)); if (!marquee.length) { root.innerHTML = ''; return; } const speed = Math.min(90, Math.max(8, Number(marquee[0].marqueeSpeed || 22))); const trackMarkup = [...marquee, ...marquee].map((banner, index) => bannerCard(banner, index >= marquee.length ? 'is-duplicate' : '')).join(''); root.innerHTML = `<section class="marketing-marquee section-wrap" aria-label="Current Rinova offers"><div class="marketing-marquee-window"><div class="marketing-marquee-track" style="--marquee-duration:${speed}s">${trackMarkup}</div></div></section>`; marquee.forEach((banner) => track('view_promotion', { promotion_id: String(banner.id || banner.title || 'rinova-promotion'), promotion_name: banner.title || 'Rinova promotion', creative_slot: 'marquee' })); }
function closeOfferPopup() { const root = $('#offer-popup-root'); if (!root) return; const id = root.dataset.bannerId; if (id) { try { sessionStorage.setItem(`rinova-popup-dismissed-${id}`, '1'); } catch {} } root.classList.remove('open'); root.setAttribute('aria-hidden', 'true'); window.setTimeout(() => { root.innerHTML = ''; }, 220); }
function showOfferPopup(banners) { const root = $('#offer-popup-root'); if (!root) return; const popup = (banners || []).find((banner) => banner.placement === 'popup' && bannerMatchesFilter(banner)); if (!popup) return; try { if (sessionStorage.getItem(`rinova-popup-dismissed-${popup.id}`)) return; } catch {} root.dataset.bannerId = String(popup.id || ''); const href = String(popup.linkUrl || '').trim(); const body = `${bannerVisual(popup)}<div class="offer-popup-copy">${bannerContent(popup)}${href ? `<span class="offer-popup-cta">Explore the offer ${icon('arrowUpRight')}</span>` : ''}</div>`; root.innerHTML = `<div class="offer-popup-backdrop" data-close-offer></div><section class="offer-popup-card" role="dialog" aria-modal="true" aria-label="${escapeHtml(popup.title || 'Rinova offer')}">${href ? `<a class="offer-popup-link" data-promotion-id="${escapeHtml(String(popup.id || popup.title || 'rinova-popup'))}" data-promotion-name="${escapeHtml(popup.title || 'Rinova offer')}" href="${escapeHtml(href)}">${body}</a>` : body}<button class="offer-popup-close" type="button" data-close-offer aria-label="Close offer">${icon('close')}</button></section>`; root.classList.add('open'); root.setAttribute('aria-hidden', 'false'); track('view_promotion', { promotion_id: String(popup.id || popup.title || 'rinova-popup'), promotion_name: popup.title || 'Rinova offer', creative_slot: 'popup' }); root.querySelectorAll('[data-close-offer]').forEach((node) => node.addEventListener('click', closeOfferPopup)); }
function applyCmsContent(data) { const notice = data.content?.find((item) => item.key === 'topbar_notice'); try { const body = JSON.parse(notice?.body || '{}'); if (body.text) document.querySelector('.announcement').childNodes[0].textContent = `${body.text} · `; } catch {} const posts = data.posts || []; const cards = document.querySelectorAll('#journal .journal-grid article'); posts.slice(0, cards.length).forEach((post, index) => { const card = cards[index]; const title = card?.querySelector('h3'); const art = card?.querySelector('.journal-art'); const label = card?.querySelector('.eyebrow'); const image = String(post.coverImageUrl || post.imageUrl || '').trim(); if (title) title.innerHTML = `<a href="/blog.html?slug=${encodeURIComponent(post.slug)}">${escapeHtml(post.title)}</a>`; if (label) label.textContent = `${post.category || 'JOURNAL'}${post.subcategory ? ` · ${post.subcategory}` : ''}${post.duration ? ` · ${post.duration}` : ''}`; if (art && /^(https:\/\/|\/assets\/|\/media\/)/i.test(image)) { art.style.backgroundImage = `url("${image.replace(/"/g, '%22')}")`; art.classList.add('has-cms-image'); } }); state.marketingBanners = data.banners || []; renderMarketingBanners(state.marketingBanners); window.setTimeout(() => showOfferPopup(state.marketingBanners), 900); }
function mountChatWidget() { const widget = document.createElement('div'); widget.innerHTML = `<button id="chat-launcher" class="chat-launcher" aria-label="Open SmartGen support">${icon('sparkle')}<span class="sr-only">Open SmartGen support</span></button><section id="chat-panel" class="chat-panel" aria-hidden="true"><div class="chat-head"><div class="smartgen-brand"><span class="smartgen-mark">SG</span><div><a class="smartgen-title" href="https://smartgentools.com" target="_blank" rel="noopener">SmartGen</a><span class="smartgen-subtitle">Rinova beauty support</span></div></div><button id="chat-close" class="chat-close" aria-label="Close support">${icon('close')}</button></div><div class="chat-choice"><button class="chat-choice-button active" data-chat-mode="ai">Ask SmartGen</button><a class="chat-choice-button" href="https://wa.me/8801738745949" target="_blank" rel="noopener">WhatsApp</a></div><div id="chat-messages" class="chat-messages"><div class="chat-bubble assistant">হ্যালো! Product, price, usage, delivery বা order নিয়ে জানতে চাইলে লিখুন।</div></div><form id="chat-form" class="chat-form"><input id="chat-input" placeholder="আপনার প্রশ্ন লিখুন…" autocomplete="off" required /><button aria-label="Send message">${icon('arrowRight')}</button></form></section>`; document.body.appendChild(widget); $('#chat-launcher').addEventListener('click', () => { const panel = $('#chat-panel'); panel.classList.toggle('open'); panel.setAttribute('aria-hidden', String(!panel.classList.contains('open'))); }); $('#chat-close').addEventListener('click', () => { const panel = $('#chat-panel'); panel.classList.remove('open'); panel.setAttribute('aria-hidden', 'true'); }); $('#chat-form').addEventListener('submit', sendCustomerChat); }
function renderChatMessages() { const node = $('#chat-messages'); node.innerHTML = `<div class="chat-bubble assistant">হ্যালো! Product, price, usage, delivery বা order নিয়ে জানতে চাইলে লিখুন।</div>` + state.chatMessages.map((message) => { const cards = Array.isArray(message.products) ? `<div class="chat-product-list">${message.products.map((product) => { const href = `/products/${encodeURIComponent(String(product.slug || ''))}${state.adminPreview ? '?admin_preview=1' : ''}`; const image = /^(https:\/\/|\/assets\/)/i.test(String(product.imageUrl || '')) ? product.imageUrl : '/assets/beauty-flatlay.jpg'; return `<a class="chat-product-card" href="${escapeHtml(href)}"><img src="${escapeHtml(image)}" alt="${escapeHtml(product.name)}" loading="lazy"><span class="chat-product-card-copy"><small>${escapeHtml(product.categoryName || 'Rinova edit')}</small><strong>${escapeHtml(product.name)}</strong><b>${money(product.price)}${Number(product.stock || 0) <= 0 ? ' <i>Stock out</i>' : ''}</b></span><span class="chat-product-arrow" aria-hidden="true">${icon('arrowUpRight')}</span></a>`; }).join('')}</div>` : ''; return `<div class="chat-bubble ${message.role}">${escapeHtml(message.content)}${cards}</div>`; }).join(''); node.scrollTop = node.scrollHeight; }
async function sendCustomerChat(event) { event.preventDefault(); const input = $('#chat-input'); const content = input.value.trim(); if (!content) return; input.value = ''; state.chatMessages.push({ role: 'user', content }); renderChatMessages(); input.disabled = true; try { const data = await api('/chat/customer', { method: 'POST', body: JSON.stringify({ visitorKey: state.visitorKey, messages: state.chatMessages }) }); state.chatMessages.push({ role: 'assistant', content: data.reply, products: data.products || [] }); renderChatMessages(); track('support_chat_message'); } catch { state.chatMessages.push({ role: 'assistant', content: 'দুঃখিত, এখন AI support পাওয়া যাচ্ছে না। WhatsApp-এ যোগাযোগ করুন: +880 1738-745949' }); renderChatMessages(); } finally { input.disabled = false; input.focus(); } }
const fallbackCategoryImages = { 'skin-care': '/assets/rinova-category-skin-care.webp', 'face-care': '/assets/rinova-category-face-care.webp', 'hair-care': '/assets/rinova-hair-category.webp', 'eyes-makeup': '/assets/rinova-eyes-category.webp', 'face-makeup': '/assets/rinova-makeup-studio.webp', 'makeup': '/assets/rinova-makeup-collection.webp', 'perfume': '/assets/rinova-perfume-category.webp' }; const fallbackCategories = ['Skin Care', 'Face Care', 'Face Makeup', 'Eyes Makeup', 'Makeup', 'Hair Care', 'Perfume', 'Kids'].map((name, index) => { const slug = name.toLowerCase().replaceAll(' ', '-'); return { name, slug, imageUrl: fallbackCategoryImages[slug] || (index % 3 === 0 ? '/assets/skincare-products.jpg' : index % 3 === 1 ? '/assets/beauty-flatlay.jpg' : '/assets/skincare-model.jpg') }; });
const fallbackProducts = [
  { id: 1, name: 'Dew Ritual Hydrating Serum', slug: 'dew-ritual-hydrating-serum', description: 'A lightweight daily serum for soft, hydrated-looking skin.', price: 890, compareAtPrice: 1090, imageUrl: '/assets/skincare-products.jpg', stock: 24, rating: 4.8, categoryName: 'Skin Care', categorySlug: 'skin-care', featured: 1 },
  { id: 2, name: 'Cloud Cleanse Gentle Face Wash', slug: 'cloud-cleanse-gentle-face-wash', description: 'A gentle cleanser for a fresh, comfortable finish.', price: 590, compareAtPrice: 690, imageUrl: '/assets/beauty-flatlay.jpg', stock: 32, rating: 4.7, categoryName: 'Face Care', categorySlug: 'face-care', featured: 1 },
  { id: 3, name: 'Soft Glow SPF 50 Sunscreen', slug: 'soft-glow-spf-50-sunscreen', description: 'A smooth daily sunscreen with a comfortable, non-heavy finish.', price: 780, compareAtPrice: 950, imageUrl: '/assets/skincare-model.jpg', stock: 18, rating: 4.9, categoryName: 'Skin Care', categorySlug: 'skin-care', featured: 1 },
  { id: 4, name: 'Rose Petal Lip Tint', slug: 'rose-petal-lip-tint', description: 'A buildable rosy tint for an effortless everyday look.', price: 450, compareAtPrice: 520, imageUrl: '/assets/beauty-flatlay.jpg', stock: 40, rating: 4.6, categoryName: 'Makeup', categorySlug: 'makeup', featured: 0 },
  { id: 5, name: 'Radiant Glow Makeup Edit', slug: 'radiant-glow-makeup-edit', description: 'A polished makeup edit for radiant everyday looks.', price: 1290, compareAtPrice: 1590, imageUrl: '/assets/rinova-makeup-flatlay-wide.png', stock: 18, rating: 4.8, categoryName: 'Makeup', categorySlug: 'makeup', featured: 1 },
  { id: 6, name: 'The Complete Makeup Collection', slug: 'complete-makeup-collection', description: 'A curated collection of complexion, eye and lip essentials.', price: 1890, compareAtPrice: 2290, imageUrl: '/assets/rinova-makeup-collection.png', stock: 14, rating: 4.9, categoryName: 'Makeup', categorySlug: 'makeup', featured: 1 },
  { id: 7, name: 'Everyday Makeup Essentials', slug: 'everyday-makeup-essentials', description: 'A versatile studio-inspired selection for your daily routine.', price: 1490, compareAtPrice: 1790, imageUrl: '/assets/rinova-makeup-studio.png', stock: 20, rating: 4.7, categoryName: 'Makeup', categorySlug: 'makeup', featured: 1 },
  { id: 8, name: 'Pink Glow Lip & Blush Edit', slug: 'pink-glow-lip-blush-edit', description: 'A soft pink edit of lip colour, gloss and luminous blush.', price: 990, compareAtPrice: 1190, imageUrl: '/assets/rinova-pink-lip-edit.png', stock: 25, rating: 4.8, categoryName: 'Makeup', categorySlug: 'makeup', featured: 1 },
  { id: 9, name: 'Glow Bloom Skincare Duo', slug: 'glow-bloom-skincare-duo', description: 'A radiant skincare pairing for a soft, hydrated-looking finish.', price: 1190, compareAtPrice: 1490, imageUrl: '/assets/rinova-glow-skincare.png', stock: 16, rating: 4.9, categoryName: 'Skin Care', categorySlug: 'skin-care', featured: 1 },
  { id: 10, name: 'Blush & Bloom Gift Set', slug: 'blush-and-bloom-gift-set', description: 'A thoughtful multi-piece self-care set for gifting or your own ritual.', price: 1690, compareAtPrice: 1990, imageUrl: '/assets/rinova-blush-bloom-set.png', stock: 12, rating: 4.8, categoryName: 'Skin Care', categorySlug: 'skin-care', featured: 1 },
  { id: 11, name: 'Beet + Vitamin A Serum Shot', slug: 'beet-vitamin-a-serum-shot', description: 'A targeted serum shot for a smoother, refreshed-looking complexion.', price: 790, compareAtPrice: 950, imageUrl: '/assets/rinova-vitamin-serum.png', stock: 22, rating: 4.7, categoryName: 'Skin Care', categorySlug: 'skin-care', featured: 0 },
  { id: 12, name: 'Rose Water 70% Glow Serum', slug: 'rose-water-70-glow-serum', description: 'A light, luminous serum for a dewy everyday skincare ritual.', price: 890, compareAtPrice: 1090, imageUrl: '/assets/rinova-rose-serum.png', stock: 20, rating: 4.8, categoryName: 'Skin Care', categorySlug: 'skin-care', featured: 0 },
  { id: 13, name: 'Pink Petal Pressed Blush', slug: 'pink-petal-pressed-blush', description: 'A soft pressed blush for a fresh, naturally flushed finish.', price: 590, compareAtPrice: 690, imageUrl: '/assets/rinova-blush-pink-editorial.png', stock: 28, rating: 4.8, categoryName: 'Makeup', categorySlug: 'makeup', featured: 1 },
  { id: 14, name: 'Rose Gold Blush Duo', slug: 'rose-gold-blush-duo', description: 'A luminous blush duo with soft rosy tones for buildable colour.', price: 690, compareAtPrice: 790, imageUrl: '/assets/rinova-blush-duo.png', stock: 24, rating: 4.7, categoryName: 'Makeup', categorySlug: 'makeup', featured: 1 },
  { id: 15, name: 'Marble Rose Baked Blush', slug: 'marble-rose-baked-blush', description: 'A marbled baked blush for a warm, polished everyday glow.', price: 620, compareAtPrice: 750, imageUrl: '/assets/rinova-marble-blush.png', stock: 26, rating: 4.6, categoryName: 'Makeup', categorySlug: 'makeup', featured: 0 },
  { id: 23, name: 'Gloss Absolu Hair Ritual', slug: 'gloss-absolu-hair-ritual', description: 'A polished demo hair-care edit featuring cleansing, conditioning and finishing care.', price: 999, compareAtPrice: 1290, imageUrl: '/assets/rinova-hair-gloss-ritual.webp', stock: 10, rating: 0, categoryName: 'Hair Care', categorySlug: 'hair-care', featured: 0 },
  { id: 24, name: 'Hair Tools and Styling Edit', slug: 'hair-tools-and-styling-edit', description: 'A practical demo edit of brushes, styling tools and finishing essentials for everyday hair care.', price: 1290, compareAtPrice: 1590, imageUrl: '/assets/rinova-hair-tools-edit.webp', stock: 10, rating: 0, categoryName: 'Hair Care', categorySlug: 'hair-care', featured: 0 },
  { id: 25, name: 'Everyday Hair Care Essentials', slug: 'everyday-hair-care-essentials', description: 'A soft, everyday hair-care selection presented for the Rinova catalogue preview.', price: 1490, compareAtPrice: 1890, imageUrl: '/assets/rinova-hair-essentials.webp', stock: 10, rating: 0, categoryName: 'Hair Care', categorySlug: 'hair-care', featured: 0 },
  { id: 26, name: 'Soft Line Eye Definer', slug: 'soft-line-eye-definer', description: 'A temporary demo eye-makeup listing for a defined everyday look.', price: 490, compareAtPrice: 650, imageUrl: '/assets/rinova-eyes-product-01.webp', stock: 10, rating: 0, categoryName: 'Eyes Makeup', categorySlug: 'eyes-makeup', featured: 0 },
  { id: 27, name: 'Rose Eye Glow Edit', slug: 'rose-eye-glow-edit', description: 'A soft rose-toned eye-makeup edit for an easy polished finish.', price: 690, compareAtPrice: 850, imageUrl: '/assets/rinova-eyes-product-02.webp', stock: 10, rating: 0, categoryName: 'Eyes Makeup', categorySlug: 'eyes-makeup', featured: 0 },
  { id: 28, name: 'Everyday Eye Colour Palette', slug: 'everyday-eye-colour-palette', description: 'A temporary demo eye-colour palette listing for the Rinova catalogue.', price: 790, compareAtPrice: 990, imageUrl: '/assets/rinova-eyes-product-03.webp', stock: 10, rating: 0, categoryName: 'Eyes Makeup', categorySlug: 'eyes-makeup', featured: 0 },
  { id: 29, name: 'Midnight Eye Glam Edit', slug: 'midnight-eye-glam-edit', description: 'A deeper eye-makeup edit for evening looks and special plans.', price: 890, compareAtPrice: 1090, imageUrl: '/assets/rinova-eyes-product-04.webp', stock: 10, rating: 0, categoryName: 'Eyes Makeup', categorySlug: 'eyes-makeup', featured: 0 },
  { id: 30, name: 'Soft Focus Eye Essentials', slug: 'soft-focus-eye-essentials', description: 'An easy eye-makeup essentials listing for a clean, soft finish.', price: 590, compareAtPrice: 750, imageUrl: '/assets/rinova-eyes-product-05.webp', stock: 10, rating: 0, categoryName: 'Eyes Makeup', categorySlug: 'eyes-makeup', featured: 0 },
  { id: 31, name: 'Classic Eye Detail Kit', slug: 'classic-eye-detail-kit', description: 'A temporary demo eye-detail kit for shaping and finishing the eye look.', price: 650, compareAtPrice: 820, imageUrl: '/assets/rinova-eyes-product-06.webp', stock: 10, rating: 0, categoryName: 'Eyes Makeup', categorySlug: 'eyes-makeup', featured: 0 },
  { id: 32, name: 'Pink Cloud Eau de Parfum', slug: 'pink-cloud-eau-de-parfum', description: 'A soft pink fragrance profile presented as a temporary Rinova demo listing.', price: 990, compareAtPrice: 1290, imageUrl: '/assets/rinova-perfume-product-01.webp', stock: 10, rating: 0, categoryName: 'Perfume', categorySlug: 'perfume', featured: 0 },
  { id: 33, name: 'Peach Veil Fragrance Mist', slug: 'peach-veil-fragrance-mist', description: 'A warm peach-toned fragrance edit for a soft everyday mood.', price: 790, compareAtPrice: 990, imageUrl: '/assets/rinova-perfume-product-02.webp', stock: 10, rating: 0, categoryName: 'Perfume', categorySlug: 'perfume', featured: 0 },
  { id: 34, name: 'Noir Rose Signature Scent', slug: 'noir-rose-signature-scent', description: 'A rich rose fragrance profile for evening rituals and statement moments.', price: 1190, compareAtPrice: 1490, imageUrl: '/assets/rinova-perfume-product-03.webp', stock: 10, rating: 0, categoryName: 'Perfume', categorySlug: 'perfume', featured: 0 },
  { id: 35, name: 'Coco Blush Fragrance Edit', slug: 'coco-blush-fragrance-edit', description: 'A polished fragrance edit with a warm, luminous visual mood.', price: 1090, compareAtPrice: 1390, imageUrl: '/assets/rinova-perfume-product-04.webp', stock: 10, rating: 0, categoryName: 'Perfume', categorySlug: 'perfume', featured: 0 }
];
async function init() { mountChatWidget(); try { const [categories, products, content] = await Promise.all([api('/categories'), api('/products'), api('/content/home')]); renderCategories(categories.categories); state.products = products.products; renderProducts(); applyCmsContent(content); } catch (error) { renderCategories(fallbackCategories); state.products = fallbackProducts; renderProducts(); toast('Preview mode: showing curated Rinova products'); console.error(error); } renderBag(); }
document.addEventListener('click', (event) => { const action = event.target.closest('[data-action]')?.dataset.action; if (action === 'menu') toggleMobileNav(true); if (action === 'close-menu') toggleMobileNav(false); if (event.target.id === 'mobile-nav-backdrop') toggleMobileNav(false); if (action === 'bag') toggleDrawer(true); if (action === 'close-bag') toggleDrawer(false); if (action === 'checkout') checkout(); if (action === 'search') openSearch(); if (action === 'close-search') closeSearch(); const suggestion = event.target.closest('[data-search-suggestion]')?.dataset.searchSuggestion; if (suggestion) { $('#site-search').value = suggestion; $('#search-form').requestSubmit(); } });
document.querySelectorAll('.mobile-nav a').forEach((link) => link.addEventListener('click', () => toggleMobileNav(false)));
document.querySelectorAll('.filter').forEach((button) => button.addEventListener('click', () => { state.filter = button.dataset.filter; document.querySelectorAll('.filter').forEach((filter) => filter.classList.toggle('active', filter === button)); renderProducts(); renderMarketingBanners(state.marketingBanners); track('product_filter', { filter: state.filter }); }));
$('#newsletter-form').addEventListener('submit', async (event) => { event.preventDefault(); const form = event.target; const input = form.elements.namedItem('email'); const message = $('#newsletter-message'); const email = String(input?.value || '').trim(); if (!email) return; if (message) message.textContent = 'Joining…'; try { const data = await api('/newsletter', { method: 'POST', body: JSON.stringify({ email, source: 'footer' }) }); if (message) message.textContent = data.message || 'You are on the softer list.'; toast('You are on the softer list.'); form.reset(); track('newsletter_signup', { source: 'footer' }); } catch (error) { if (message) message.textContent = error.message || 'Could not save your email right now.'; } });

document.addEventListener('click', (event) => { if (event.target.closest('[data-close-offer]')) closeOfferPopup(); const promotion = event.target.closest('[data-promotion-id]'); if (promotion) track('select_promotion', { promotion_id: promotion.dataset.promotionId, promotion_name: promotion.dataset.promotionName, creative_slot: 'marquee' }); });
$('#search-form').addEventListener('submit', submitSearch);
$('#search-overlay').addEventListener('click', (event) => { if (event.target.classList.contains('search-overlay-backdrop')) closeSearch(); });
document.addEventListener('keydown', (event) => { if (event.key === 'Escape') closeSearch(); });
$('#bag-drawer').addEventListener('click', (event) => { if (event.target.id === 'bag-drawer') toggleDrawer(false); });
init();
