const API_BASE = window.location.hostname.includes('localhost') ? 'http://localhost:8787/api' : '/api';
const state = { bag: JSON.parse(localStorage.getItem('rinova-bag') || '[]') };
const $ = (selector) => document.querySelector(selector);
const money = (value) => `৳${Number(value || 0).toLocaleString('en-BD')}`;
const escapeHtml = (value) => String(value ?? '').replace(/[&<>"']/g, (char) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[char]));
async function api(path) { const response = await fetch(`${API_BASE}${path}`); const data = await response.json().catch(() => ({})); if (!response.ok) throw new Error(data.error || 'Product unavailable'); return data; }
function updateBagCount() { $('#detail-bag-count').textContent = state.bag.reduce((sum, item) => sum + Number(item.quantity || 0), 0); }
function addToBag(product, quantity) { const existing = state.bag.find((item) => Number(item.id) === Number(product.id)); if (existing) existing.quantity += quantity; else state.bag.push({ id: product.id, name: product.name, price: product.price, imageUrl: product.imageUrl, quantity }); localStorage.setItem('rinova-bag', JSON.stringify(state.bag)); updateBagCount(); $('#detail-status').textContent = `${product.name} added to your bag.`; }
function render(product) { const tiers = (() => { try { return JSON.parse(product.volumeTiersJson || '[]'); } catch { return []; } })(); const tierText = tiers.length ? `<div class="detail-note"><strong>Volume pricing available.</strong><br>${tiers.map((tier) => `${tier.minQty}+ units · ${money(tier.price)} each`).join(' · ')}</div>` : ''; $('#detail-root').innerHTML = `<div class="detail-grid"><div class="detail-media"><img src="${escapeHtml(product.imageUrl || '/assets/beauty-flatlay.jpg')}" alt="${escapeHtml(product.name)}"></div><section class="detail-copy"><p class="eyebrow">${escapeHtml(product.categoryName || 'Rinova edit')} · ${product.stock > 0 ? 'IN STOCK' : 'SOLD OUT'}</p><h1>${escapeHtml(product.name)}</h1><p>${escapeHtml(product.description || product.shortDescription || 'A thoughtful choice for your everyday ritual.')}</p><div class="detail-price"><strong>${money(product.price)}</strong>${product.compareAtPrice ? `<del>${money(product.compareAtPrice)}</del>` : ''}</div><div class="detail-controls"><input id="detail-quantity" type="number" min="${Math.max(1, Number(product.minOrderQty || 1))}" max="${Math.max(1, Number(product.stock || 0))}" value="${Math.max(1, Number(product.minOrderQty || 1))}" aria-label="Quantity"><button id="detail-add" class="button button-dark" ${product.stock < 1 ? 'disabled' : ''}>Add to bag <span>+</span></button><button id="detail-buy" class="button" ${product.stock < 1 ? 'disabled' : ''}>Buy now <span>→</span></button></div><p id="detail-status" class="detail-status"></p><div class="detail-facts"><div>Weight<strong>${Number(product.weightGrams || 0) ? `${product.weightGrams}g` : '—'}</strong></div><div>Availability<strong>${product.stock > 0 ? `${product.stock} ready to ship` : 'Sold out'}</strong></div><div>Delivery<strong>৳90 Dhaka · ৳150 outside</strong></div><div>Support<strong><a href="https://wa.me/8801738745949">WhatsApp us</a></strong></div></div>${tierText}</section></div>`; const quantity = () => Math.max(1, Math.min(Number(product.stock || 0), Number($('#detail-quantity').value || 1))); $('#detail-add')?.addEventListener('click', () => addToBag(product, quantity())); $('#detail-buy')?.addEventListener('click', () => { addToBag(product, quantity()); window.location.href = '/checkout.html'; }); document.title = `${product.name} · Rinova BD`; }
(async function boot() { updateBagCount(); try { const slug = new URLSearchParams(window.location.search).get('slug'); if (!slug) throw new Error('Product not found'); const data = await api(`/products/${encodeURIComponent(slug)}`); render(data.product); } catch (error) { $('#detail-root').innerHTML = `<div class="loading">${escapeHtml(error.message)}<br><a class="detail-back" href="/#shop">Return to shop →</a></div>`; } }());
